language: node_js
node_js:
  - 'iojs'
  - '0.10'
  - '0.12'
  - '1'
  - '2'
  - '4'
  - '5'
sudo: false
matrix:
  allow_failures:
    - node_js: '0.10'
    - node_js: 'iojs'
  fast_finish: true
install: npm install
script: npm test