dist: trusty
language: node_js
node_js:
  - 'node'
  - '4'
  - '5'
  - '6'
install: npm install
script: npm test
sudo: required
osx_image: xcode8
os:
  - linux
  - osx
before_script:
  - wget https://s3-us-west-2.amazonaws.com/opencollada-pr-artifacts/jobs/deploy-artifacts-to-s3/1005/opencollada_OCPR-502_OCTESTSPR-14_openCOLLADA-ubuntu-pull-request_build_257.zip -O /tmp/OpenCollada.zip
  - unzip /tmp/OpenCollada.zip
  - export PATH=$PATH:$PWD/tmp/bin/
